language: node_js
os: linux
script: npm run build && npm run lint
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
notifications:
  slack:
    secure: b6sf3svOlJfS/ZdP0sGMASNWY8H7vhwLZCzVI93KQZxe2i2KbHo0/157VXVaDDBrvsgOsgDhGOuJsqrxxNJak53bu2yZ1hLg7sdIm4oDcs9aVoW7BcnyHeK+8+uLx6rOQMmncpJdVxyMAE9IMlqNPyVBmX2T4iQycifvV4VpJ2iHF3iVI1P0X19uP5b9jU1HfXBl+UaARngnXIk+4Zg6UvT6Q0L4k7oW90rnkv8Hrx8xerjtcsEPcwDMqIHfUl87sc5xnVrGcX9lapZEgsLfnJtxyX23mQNGggY4Imj9ObVQnV1zqpay4Eh3UMpRuRkGrnKSXnCASlbft5rg54BFqBiQOoO1AnR+0LM3zTozDk2xAK4la+OLPkrvkpweo6KS5dhktYrZQW7cnwJpWiwiP6fjO91LhsjxEJYv3/i7cb8lESW1wuRlWmm3IULG/h74gRNecCK6ITugDiXgkPXi5OkXEDRfj0M8G38w9I0D2SC2GbjL+lw38K5IhlT3iEkfzJVNMLit2fjvh4+wlur39rvDqm21PbKXOfW0khdAK7NyQgEvgNA/XfJ8SxL5eLz5GnsnbgNJNp8/1Xz2moCMXTlec18fOeOrYBXSVALQBEG5dKcOEa83Y5pTI7n6OwacwduSzlqf+UL5f9cd8OtfFsdsHNEmm1tppybIdg13kVU=
