language: node_js
os: linux
script: npm run build && npm run lint
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
notifications:
  slack:
    secure: $GITHUB_NOTIFICATION_TOKEN
